### ISSUE TITLE
Scroll to bottom of chatbox when user sends message

### ISSUE THREAD

**Issue by nsteward96** [nsteward96/Sovereign#61]
When a user sends a message that exceeds the height of the chatbox, it pushes it below the current scroll and the user has to scroll to see what they said. It should default to scroll to the bottom so the user can see the latest chat post. Also, if the user is scrolling up in the chat or is otherwise not already scrolled to the bottom when the other user(s) sends their message, the box should not force to the bottom, because the user may be looking up an older post and doesn't want to be stopped because chat is being spammed.

**Comment by nsteward96** [comment]
Answer from [here:](https://stackoverflow.com/questions/18614301/keep-overflow-div-scrolled-to-bottom-unless-user-scrolls-up)

"I was able to get this working with CSS only.

The trick is to use `display: flex;` and `flex-direction: column-reverse;`

The browser treats the bottom like its the top. Assuming the browsers you're targeting support flex-box, the only caveat is that the markup has to be in reverse order.

Here is a working example. https://codepen.io/jimbol/pen/YVJzBg"

**Comment by thaibucher** [comment]
When using flex elements, the markup does not actually need to be in reverse order, You can add the order property to the element's css to tell it where to go.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items

**Comment by nsteward96** [comment]
@thaibucher I did need to start prepending my messages to the message box instead of appending, which I believe means they did need to be in reverse order.
